# Generated by Django 2.2 on 2021-05-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos_and_ninjas_app', '0003_ninja_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='desc',
        ),
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default='old dojo'),
        ),
    ]
